import Head from 'next/head'
import Herosection from '../components/Herosection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Herosection title={"Let's Watch Movie Together"} url={'/images/hero-image.jpg'} />
    </>
  )
}
